
logging:
  level:
    io.asyncer.r2dbc.mysql.client: DEBUG # for database initialization
    io.asyncer.r2dbc.mysql.QUERY: DEBUG # for queries
    io.asyncer.r2dbc.mysql.PARAM: DEBUG # for parameters
    org:
      springframework:
        web:
          server: trace
spring:
  codec:
    max-in-memory-size: 8MB