
logging:
  level:
    io.r2dbc.postgresql.client: DEBUG # for database initialization
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
    org:
      springframework:
        web:
          server: trace
spring:
  codec:
    max-in-memory-size: 8MB